use testbd2;

create table pays (
	code_pays CHAR(2),
	pays VARCHAR(50)
);
insert into pays 
(code_pays, pays) 
values 
('PH', 'Philippines'),
('CN', 'China'),
('PE', 'Peru'),
('ID', 'Indonesia'),
('SI', 'Slovenia'),
('PK', 'Pakistan'),
('PH', 'Philippines'),
('CN', 'China'),
('SI', 'Slovenia'),
('CN', 'China'),
('HN', 'Honduras'),
('IR', 'Iran'),
('FR', 'France'),
('AR', 'Argentina'),
('ID', 'Indonesia'),
('SE', 'Sweden'),
('MQ', 'Martinique'),
('SA', 'Saudi Arabia'),
('UA', 'Ukraine'),
('CN', 'China'),
('RU', 'Russia'),
('RU', 'Russia'),
('CN', 'China'),
('RU', 'Russia'),
('TH', 'Thailand'),
('GT', 'Guatemala'),
('ID', 'Indonesia'),
('PS', 'Palestinian Territory'),
('GR', 'Greece'),
('XK', 'Kosovo'),
('SR', 'Suriname'),
('PH', 'Philippines'),
('ID', 'Indonesia'),
('RU', 'Russia'),
('CN', 'China'),
('CN', 'China'),
('PL', 'Poland'),
('RU', 'Russia'),
('PT', 'Portugal'),
('KZ', 'Kazakhstan'),
('SE', 'Sweden'),
('IE', 'Ireland'),
('IR', 'Iran'),
('AR', 'Argentina'),
('CN', 'China'),
('DO', 'Dominican Republic'),
('AL', 'Albania'),
('ID', 'Indonesia');
